### ISSUE TITLE
file extensions JPEG, RAF

### ISSUE THREAD

**Issue by cebra-ffm** [haukesomm/apple-photos-export#1]
Hauke,

great work, seems to help a lot managing my various libs. 
But I run in some issues with file extensions generating errors - RAF (strange fuji extension) and JPEG. 
Any chance to integrate it in here?
thank you,
Christian

**Comment by haukesomm** [comment]
Hi Christian and thanks for reaching out!

I'd love to include the missing file type! Since I don't have any RAF images in my own library: Could you provide me with a minimal library containing nothing but a single RAF image and maybe a failing JPEG? This way I can look into the database's internals and reverse-engineer how those file type is handled.

As JPEG should already work: Do you have more information on what exactly happens when you try to export JPEG images? Is there a specific error message, for example?

Kind regards
Hauke

**Comment by cebra-ffm** [comment]
Hauke,
I have created separate photo libs with  BMP and RAF, here to download: https://nx1230.your-storageshare.de/s/2FDgHdn6GyjYiXY
They do fail with _Unknown extension: bmp_ // _Unknown extension: raf_.
Still searching for my JPEG failure example...
Any chance to have the error a bit more verbose, like naming the file which fails? Sorry, no rust expert here...
kind regards,
Christian

**Comment by cebra-ffm** [comment]
ha, now catched a _Unknown extension: JPG_
[apple-photos-export-9eXMoTEv.log](https://github.com/user-attachments/files/17555992/apple-photos-export-9eXMoTEv.log)
But hard to say which one of the pictures is the bad one, too many of them

**Comment by haukesomm** [comment]
Thanks for sharing! I'll have a look at it when I have some spare time in the next days 👍🏻 

> Any chance to have the error a bit more verbose, like naming the file which fails?

Yeah, that's definitely needed and already on my to-do list

**Comment by haukesomm** [comment]
Support for both `.bmp` and `.raf` files has been added with the new 0.4.1 patch release. The new version can be installed by running `brew upgrade`.

The new version also includes an attempt at fixing the JPEG related bug. Feel free to re-open this issue if the issues persist.

More expressive logging is not included in this version and will be added at a later point in time. Progress is tracked in #3.
